name: ci-sonarcloud
on: [push]
jobs:
  run-ci:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node v15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: yarn install
      - run: yarn test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}